const lessons = lessonData.lessons;
const $ = (id) => document.getElementById(id);
const views = { lessons: $('lesson-view'), quiz: $('quiz-view'), result: $('result-view') };
let state = { code: null, words: [], deck: [], current: null, direction: 'primary', correct: 0, errors: 0, hintsUsed: 0, answered: false };
function lessonFor(code) { return lessons.find((lesson) => lesson.code === code); }
function wordsFor(code) { return lessonFor(code)?.words || []; }
function titleFor(code) { return lessonFor(code)?.title || `Lekce ${code}`; }
function normalize(value) { return value.trim().replace(/\s+/g, ' '); }
function shuffle(items) { const result = [...items]; for (let i = result.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
function show(view) { Object.values(views).forEach((item) => { item.hidden = item !== view; }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderLessons(filter = '') { const query = normalize(filter); const list = $('lesson-list'); list.innerHTML = ''; const available = lessons.filter((lesson) => lesson.visible && (lesson.title + ' ' + lesson.code).toLocaleLowerCase('cs-CZ').includes(query)); $('lesson-count').textContent = `${available.length} lekcí`; $('empty-lessons').hidden = available.length !== 0; available.forEach((lesson) => { const code = lesson.code; const button = document.createElement('button'); button.type = 'button'; button.className = 'lesson-button'; button.innerHTML = `<span class="lesson-code">${code}</span><span><span class="lesson-name">${titleFor(code)}</span><span class="lesson-meta">${wordsFor(code).length} ${wordsFor(code).length === 1 ? 'položka' : 'slov'}</span></span>`; button.addEventListener('click', () => startQuiz(code)); list.appendChild(button); }); }
function selectedDirection() { if (state.direction === 'mixed') return Math.random() > .5 ? 'primary' : 'reverse'; return state.direction; }
function startQuiz(code) { state = { ...state, code, words: wordsFor(code), deck: shuffle(wordsFor(code)), current: null, correct: 0, errors: 0, hintsUsed: 0, answered: false }; $('direction-select').value = state.direction; updateHintButton(); show(views.quiz); nextQuestion(); }
function nextQuestion() { if (state.deck.length === 0) return finishQuiz(); state.current = { values: state.deck[0], direction: selectedDirection() }; state.answered = false; const prompt = state.code === 'C1' ? 'Napiš libovolné vyjmenované slovo po M' : state.current.direction === 'primary' ? state.current.values[0] : state.current.values[1]; $('prompt-label').textContent = titleFor(state.code); $('question').textContent = prompt; $('question-number').textContent = `Zbývá ${state.deck.length} z ${state.words.length}`; $('progress-text').textContent = `${state.words.length - state.deck.length} / ${state.words.length}`; $('progress-bar').style.width = `${((state.words.length - state.deck.length) / state.words.length) * 100}%`; $('feedback').hidden = true; $('answer').value = ''; $('answer').disabled = false; $('answer').focus(); $('answer-form').querySelector('.primary-button').innerHTML = 'Zkontrolovat <span>Enter ↵</span>'; $('correct-score').textContent = state.correct; $('wrong-score').textContent = state.errors; updateHintButton(); }
function checkAnswer(event) { event.preventDefault(); if (state.answered) return nextQuestion(); const answer = normalize($('answer').value); const expectedText = state.current.direction === 'primary' ? state.current.values[1] : state.current.values[0]; const expected = normalize(expectedText); const feedback = $('feedback'); const submitButton = $('answer-form').querySelector('.primary-button'); state.attempts++; if (!answer) { feedback.className = 'feedback wrong'; feedback.textContent = 'Napiš nejdřív nějakou odpověď.'; feedback.hidden = false; return; } if (answer === expected) { state.correct++; state.deck.shift(); state.answered = true; feedback.className = 'feedback correct'; feedback.textContent = 'Správně!'; feedback.hidden = false; $('answer').disabled = true; submitButton.textContent = state.deck.length ? 'Další otázka →' : 'Zobrazit výsledek'; } else { state.errors++; if (state.deck.length > 1) { const nextIndex = 1 + Math.floor(Math.random() * (state.deck.length - 1)); [state.deck[0], state.deck[nextIndex]] = [state.deck[nextIndex], state.deck[0]]; } feedback.className = 'feedback wrong'; feedback.innerHTML = `Ještě ne. Správná odpověď je <strong>${expectedText}</strong>.`; feedback.hidden = false; state.answered = true; $('answer').disabled = true; submitButton.textContent = 'Další otázka →'; } $('correct-score').textContent = state.correct; $('wrong-score').textContent = state.errors; submitButton.focus(); }
function updateHintButton() { const button = $('hint-button'); button.textContent = `Ukázat odpověď (${state.hintsUsed}/3)`; button.disabled = state.hintsUsed >= 3; }
function showHint() { if (state.answered || state.hintsUsed >= 3) return; const expected = state.current.direction === 'primary' ? state.current.values[1] : state.current.values[0]; state.hintsUsed++; const feedback = $('feedback'); feedback.className = 'feedback'; feedback.textContent = `Odpověď: ${expected}`; feedback.hidden = false; updateHintButton(); }
function finishQuiz() { const total = state.correct + state.errors; const percent = total ? Math.round((state.correct / total) * 100) : 0; $('result-title').textContent = percent >= 90 ? 'Skvělá práce!' : percent >= 70 ? 'Dobrá práce!' : 'Lekce splněna'; $('result-summary').textContent = `Dokončil(a) jsi lekci ${state.code} · ${titleFor(state.code)}.`; $('result-correct').textContent = state.correct; $('result-errors').textContent = state.errors; $('result-percent').textContent = `${percent} %`; show(views.result); }
$('lesson-search').addEventListener('input', (event) => renderLessons(event.target.value)); $('answer-form').addEventListener('submit', checkAnswer); $('hint-button').addEventListener('click', showHint); $('direction-select').addEventListener('change', (event) => { state.direction = event.target.value; }); $('restart-button').addEventListener('click', () => startQuiz(state.code)); $('retry-button').addEventListener('click', () => startQuiz(state.code)); $('back-button').addEventListener('click', () => show(views.lessons)); $('result-back-button').addEventListener('click', () => show(views.lessons)); renderLessons();
