const lessonData = 
{
  "lessons": [
    {
      "code": "512",
      "title": "Němčina - strana 10",
      "words": [
        ["bratr", "der Bruder"],
        ["bratranec", "der Cousin"],
        ["rodina", "die Familie"],
        ["sourozenec", "das Geschwister"],
        ["babička", "die Großmutter"],
        ["dědeček", "der Großvater"],
        ["znát (koho, co)", "kennen, er kennt"],
        ["sestra", "die Schwester"],
        ["syn", "der Sohn"],
        ["dcera", "die Tochter"],
        ["prarodiče (mn. č.)", "die Großeltern"],
        ["dítě", "das Kind"],
        ["rozčilovat, lézt na nervy", "nerven, er nervt"],
        ["normální", "normal"],
        ["vidět, dívat se", "sehen, er sieht"],
        ["stres", "der Stress"],
        ["sladký", "süß"],
        ["totální, úplný", "total"]
      ],
      "visible": true
    },
    {
      "code": "511",
      "title": "Angličtina 6 · What's up?",
      "words": [
        ["rada (slovní)", "advice"],
        ["blízko", "close"],
        ["nachlazení", "cold"],
        ["cítit se špatně", "feel sick"],
        ["cítit se dobře", "feel well"],
        ["trdlo, ňouma", "geek"],
        ["bolest hlavy", "headache"],
        ["domácí práce", "housework"],
        ["svědit", "itch"],
        ["hezký, upravený", "neat"],
        ["optika", "optician's"],
        ["lék proti bolesti", "painkiller"],
        ["pořádně", "properly"],
        ["odpovědět, zareagovat", "respond"],
        ["měl by", "should"],
        ["neměl by", "shouldn't"],
        ["bolest v krku", "sore throat"],
        ["zůstat vzhůru", "stay up"],
        ["bolení zubů", "toothache"],
        ["Co se děje?", "What's up?"],
        ["tabule (bílá)", "whiteboard"]
      ],
      "visible": true
    },
    {
      "code": "510",
      "title": "Němčina 2 · barvy, pomoc, hlad, jídelna",
      "words": [
        ["modrý", "blau"],
        ["žlutý", "gelb"],
        ["zelený", "grün"],
        ["oranžový", "orange"],
        ["pořádek", "die Ordnung"],
        ["růžový", "pink"],
        ["červený", "rot"],
        ["říct", "sagen, er sagt"],
        ["hrozný, strašný", "schrecklich"],
        ["černý", "schwarz"],
        ["tyrkysový", "türkis"],
        ["bílý", "weiß"],
        ["staromódní", "altmodisch"],
        ["férový", "fair"],
        ["přátelský", "freundlich"],
        ["chybný, nesprávný", "falsch"],
        ["pomoc", "die Hilfe"],
        ["hlad", "der Hunger"],
        ["pořád", "immer"],
        ["školní jídelna", "die Mensa"],
        ["svetřík", "der Pulli"],
        ["show", "die Show"]
      ],
      "visible": true
    },
    {
      "code": "509",
      "title": "Němčina 2 · vyučovací předměty, velikosti, nábytek, rodiče",
      "words": [
        ["zeměpis", "die Geografie"],
        ["dějepis", "die Geschichte"],
        ["umělecká výchova", "die Kunst"],
        ["matematika", "die Mathe"],
        ["hezký", "schön"],
        ["v (předložka + člen)", "am"],
        ["velký", "groß"],
        ["malý", "klein"],
        ["dlouhý", "lang"],
        ["učitel", "der Lehrer"],
        ["učitelka", "die Lehrerin"],
        ["úkol, úloha", "die Aufgabe"],
        ["domácí úkol", "die Hausaufgabe"],
        ["těžký", "schwer"],
        ["židle", "der Stuhl"],
        ["hodina", "die Stunde"],
        ["tabule", "die Tafel"],
        ["dveře", "die Tür"],
        ["otec", "der Vater"],
        ["týden", "die Woche"],
        ["mobilní telefon", "das Handy"],
        ["matka", "die Mutter"],
        ["správný", "richtig"]
      ],
      "visible": true
    },
    {
      "code": "508",
      "title": "Němčina 2 · dny v týdnu, vyučovací předměty",
      "words": [
        ["úterý", "der Dienstag"],
        ["polední přestávka", "die Mittagspause"],
        ["středa", "der Mittwoch"],
        ["pondělí", "der Montag"],
        ["přestávka", "die Pause"],
        ["hodina (přesný čas)", "die Uhr"],
        ["čtvrtek", "der Donnerstag"],
        ["pátek", "der Freitag"],
        ["navštívit", "besuchen, er besucht"],
        ["biologie", "die Biologie"],
        ["chemie", "die Chemie"],
        ["volný", "frei"],
        ["cizí jazyk", "die Fremdsprache"],
        ["mít", "haben, er hat"],
        ["informace", "die Info"],
        ["informatika", "die Informatik"],
        ["třída", "die Klasse"],
        ["zítra", "morgen"],
        ["fyzika", "die Physik"],
        ["sobota", "der Samstag"],
        ["škola", "die Schule"],
        ["těžiště", "der Schwerpunkt"],
        ["neděle", "der Sonntag"],
        ["rozvrh hodin", "der Stundenplan"],
        ["pracovat", "arbeiten, er arbeitet"],
        ["knihovna", "die Bibliothek"],
        ["kniha", "das Buch"],
        ["počítat", "rechnen, er rechnet"],
        ["odpočívat", "relaxen, er relaxt"]
      ],
      "visible": true
    },
    {
      "code": "507",
      "title": "Němčina 2 · kavárna, disko, kino, program",
      "words": [
        ["casting", "das Casting"],
        ["DJ", "der DJ"],
        ["natáčet", "filmen, er filmt"],
        ["vy", "ihr"],
        ["sport", "der Sport"],
        ["volejbal", "der Volleyball"],
        ["my", "wir"],
        ["zkoušet", "proben, er probt"],
        ["programovat", "programmieren, er programmiert"],
        ["kavárna", "das Café"],
        ["disko", "die Disco"],
        ["je, existuje", "es gibt"],
        ["fotka", "das Foto"],
        ["chlapec", "der Junge"],
        ["kino", "das Kino"],
        ["smát se", "lachen, er lacht"],
        ["dívka", "das Mädchen"],
        ["nový", "neu"],
        ["organizovat", "organisieren, er organisiert"],
        ["program", "das Programm"],
        ["rapovat", "rappen, er rappt"],
        ["start, začátek", "der Start"],
        ["video", "das Video"],
        ["číslo mobilního telefonu", "die Handynummer"],
        ["ulice", "die Straße"],
        ["telefonní číslo", "die Telefonnummer"]
      ],
      "visible": true
    },
    {
      "code": "506",
      "title": "Němčina 2 · e-mail, zábava, psát, legrace, zajímavý",
      "words": [
        ["e-mail", "die/das E-mail"],
        ["prázdniny (mn.č.)", "die Ferien"],
        ["pro, za", "für"],
        ["zde", "hier"],
        ["s, se", "mit"],
        ["ještě", "noch"],
        ["strýc", "der Onkel"],
        ["psát", "schreiben, er schreibt"],
        ["legrace", "der Spaß, Späße"],
        ["Dobře se bav! Příjemnou zábavu!", "Viel spaß!"],
        ["doma", "zu Hause"],
        ["aktivní", "aktiv"],
        ["inteligentní", "intelligent"],
        ["zajímavý", "interessant"],
        ["veselý", "lustig"],
        ["tancovat", "tanzen"]
      ],
      "visible": true
    },
    {
      "code": "505",
      "title": "Angličtina 5 · Dangerous situation",
      "words": [
        ["tak ... jak je možné", "as ... as possible"],
        ["prasklina, puklina", "crack"],
        ["přehrada", "dam"],
        ["poškodit", "damage"],
        ["nebezpečný", "dangerous"],
        ["diagram", "diagram"],
        ["katastrofa", "disaster"],
        ["upustit", "drop"],
        ["konec", "end"],
        ["každý", "everybody"],
        ["zaplavit", "flood"],
        ["vystoupit z", "get out of"],
        ["jít na ryby", "go fishing"],
        ["mimořádná událost", "incident"],
        ["Indonésie", "Indonesia"],
        ["přírodní", "natural"],
        ["pořádek, pořadí", "order"],
        ["parkovat", "park"],
        ["strašidelný", "scary"],
        ["výkřik", "shout"],
        ["kříčet", "shout"],
        ["zavřít", "shut"],
        ["situace", "situation"],
        ["ulice", "street"],
        ["plyšový medvídek", "teddy bear"],
        ["díky tobě", "thanks to you"],
        ["směrem k", "towards"]
      ],
      "visible": true
    },
    {
      "code": "504",
      "title": "Angličtina 5 · nepravidelná slovesa „to feel“ až „to lie“",
      "words": [
        ["cítit", "feel, felt, felt"],
        ["bojovat, prát se", "fight, fought, fought"],
        ["najít", "find, found, found"],
        ["létat", "fly, flew, flown"],
        ["dostat, získat", "get, got, got"],
        ["dát, věnovat", "give, gave, given"],
        ["jít, jet", "go, went, been/gone"],
        ["růst", "grow, grew, grown"],
        ["mít", "have, had, had"],
        ["slyšet", "hear, heard, heard"],
        ["schovat", "hide, hid, hidden"],
        ["udeřit, narazit", "hit, hit, hit"],
        ["držet", "hold, held, held"],
        ["(z)ranit se, bolet", "hurt, hurt, hurt"],
        ["udržet, chovat", "keep, kept, kept"],
        ["vědět, znát", "know, knew, known"],
        ["učit se, dozvědět se", "learn, learnt, learnt"],
        ["odejít, opustit", "leave, left, left"],
        ["ležet", "lie, lay, lain"]
      ],
      "visible": true
    },
    {
      "code": "503",
      "title": "Angličtina 5 · strana 26 až 31",
      "words": [
        ["hudební skupina", "die Band"],
        ["blbý, hloupý", "blöd"],
        ["skvělý, úžasný", "cool"],
        ["hloupý, pitomý", "doof"],
        ["jít", "gehen, er geht"],
        ["dnes", "heute"],
        ["výtečný, super", "klasse"],
        ["nudný", "langweillig"],
        ["mít rád", "mögen, er mag"],
        ["hudba, muzika", "die Musik"],
        ["ne", "nein"],
        ["ne- (zápor)", "nicht"],
        ["špatný", "schlecht"],
        ["hrát", "spielen, er spielt"],
        ["skvělý, úžasný", "toll"],
        ["basová kytara (der)", "der Bass"],
        ["basová kytara (die)", "die Bassgitarre"],
        ["flétna", "die Flöte"],
        ["housle", "die Geige"],
        ["kytara", "die Gitarre"],
        ["klávesy", "das Keyboard"],
        ["bicí (souprava)", "das Schlagzeug"],
        ["anglicky, angličtina", "Englisch"],
        ["fotografovat", "fotografieren"],
        ["poslouchat", "hören"],
        ["judo", "das Judo"],
        ["učit se", "lernen, er lernt"],
        ["dělat", "machen, er macht"],
        ["zpívat", "singen, er singt"],
        ["telefonovat", "telefonieren, er telefoniert"],
        ["stolní tenis", "das Tischtennis"],
        ["náš, naše, naše", "unser, unsere, unser"],
        ["počítač", "der Computer"],
        ["fotbal", "der Fußball"],
        ["rád/a", "gern"],
        ["basketbal", "der Basketball"],
        ["koníček", "das Hobby"],
        ["tenis", "das Tennis"],
        ["také", "auch"],
        ["kulečník", "das Billard"],
        ["tu, tady", "da"],
        ["pozdrav", "der Gruß"],
        ["kondičně běhat", "joggen, er joggt"],
        ["limonáda", "die Limo"],
        ["šachy", "das Schach"],
        ["sport", "der Sport"],
        ["teta", "die Tante"],
        ["divadlo", "das Theater"],
        ["stolní fotbal", "der Tischfußball"],
        ["mnoho", "viel, viele"]
      ],
      "visible": true
    },
    {
      "code": "502",
      "title": "Němčina 1 · číslovky, státy",
      "words": [
        ["třináct", "dreizehn"],
        ["čtrnáct", "vierzehn"],
        ["patnáct", "fünfzehn"],
        ["šestnáct", "sechzehn"],
        ["sedmnáct", "siebzehn"],
        ["osmnáct", "achtzehn"],
        ["devatenáct", "neunzehn"],
        ["dvacet", "zwanzig"],
        ["poslouchat", "zuhören"],
        ["z (předložka)", "aus"],
        ["sestřenice", "die Cousine"],
        ["Německo", "Deutschland"],
        ["Francie", "Frankreich"],
        ["přítel, kamarád", "der Freund"],
        ["Itálie", "Italien"],
        ["pocházet", "kommen"],
        ["země", "das Land"],
        ["jméno", "der Name"],
        ["číslo", "die Nummer"],
        ["Švýcarsko", "die Schweiz"],
        ["ona", "sie"],
        ["město", "die Stadt"],
        ["Turecko", "die Türkei"],
        ["kdo", "wer"],
        ["odkud", "woher"],
        ["Velká Británie", "Großbritannien"],
        ["Rakousko", "Österreich"],
        ["Polsko", "Polen"],
        ["Slovensko", "Slowakei"],
        ["Španělsko", "Spanien"],
        ["Česko", "Tschechien"],
        ["křestní jméno", "der Vorname"],
        ["co", "was"],
        ["slovo", "das Wort"],
        ["adresa", "die Adresse"],
        ["rodiče", "die Eltern"],
        ["e-mailová adresa", "die E-Mail-Adresse"],
        ["přítelkyně, kamarádka", "die Freundin"]
      ],
      "visible": true
    },
    {
      "code": "501",
      "title": "Angličtina 5 · nepravidelná slovesa „to be“ až „to fall\"",
      "words": [
        ["být", "be, was/were, been"],
        ["stát se", "become, became, become"],
        ["začít", "begin, began, begun"],
        ["kousat", "bite, bit, bitten"],
        ["zlomit, rozbít", "break, broke, broken"],
        ["přinést", "bring, brought, brought"],
        ["stavět, postavit", "build, built, built"],
        ["spálit", "burn, burnt, burnt"],
        ["koupit", "buy, bought, bought"],
        ["chytit", "catch, caught, caught"],
        ["přijít, přijet", "come, came, come"],
        ["stát (cena)", "cost, cost, cost"],
        ["stříhat, řezat", "cut, cut, cut"],
        ["hloubit, kopat", "dig, dug, dug"],
        ["dělat", "do, did, done"],
        ["kreslit", "draw, drew, drawn"],
        ["pít", "drink, drank, drunk"],
        ["řídit", "drive, drove, driven"],
        ["jíst", "eat, ate, eaten"],
        ["padat", "fall, fell, fallen"]
      ],
      "visible": true
    },
    {
      "code": "407",
      "title": "Angličtina X · Cooking",
      "words": [
        ["hlavní město", "capital"],
        ["pobřeží", "coast"],
        ["hluboký", "deep"],
        ["příšera", "monster"],
        ["široký", "wide"],
        ["úzké", "narrow"],
        ["kanál", "canal"],
        ["útes", "cliff"],
        ["pole", "field"],
        ["les", "forest"],
        ["přístav", "harbour"],
        ["ostrov", "island"],
        ["jezero", "lake"],
        ["dálnice", "motorway"],
        ["elektrárna", "power station"],
        ["mrakodrap", "skyscraper"],
        ["údolí", "valley"],
        ["přelidněný", "crowded"],
        ["rozdíl", "difference"],
        ["východ", "east"],
        ["rovinatý, plochý", "flat"],
        ["kopcovitý", "hilly"],
        ["nízký", "low"],
        ["roční období", "season"]
      ],
      "visible": true
    },
    {
      "code": "406",
      "title": "Angličtina 4 · Cooking",
      "words": [
        ["vařit", "boil"],
        ["posypat", "cover"],
        ["smažit", "fry"],
        ["strouhat", "grate"],
        ["rozpustit, roztavit", "melt"],
        ["smíchat", "mix"],
        ["oloupat, oškrábat", "peel"],
        ["škrabka", "peeler"],
        ["nalít", "pour"],
        ["krájet", "slice"],
        ["přidat", "add"],
        ["říct", "say, said"],
        ["přijít", "come, came"],
        ["spát", "sleep, slept"],
        ["psát", "write, wrote"],
        ["jíst", "eat, ate"],
        ["koupit", "buy, bought"],
        ["vidět", "see, saw"],
        ["řídit", "drive, drove"],
        ["plavat", "swim, swam"],
        ["přinést", "bring, brought"],
        ["pít", "drink, drank"],
        ["vyrobit", "make, made"],
        ["rozšířit se", "spread, spread"],
        ["růst", "grow, grew"],
        ["běžet", "run, ran"],
        ["krájet, uříznout", "cut, cut"],
        ["dát", "give, gave"],
        ["položit", "put, put"]
      ],
      "visible": true
    },
    {
      "code": "405",
      "title": "Angličtina 4 · nepravidelná slovesa",
      "words": [
        ["odejít, opustit", "leave, left"],
        ["zapomenout", "forget, forgot"],
        ["rozbít, zlomit", "break, broke"],
        ["ukrást", "steal, stole"],
        ["spadnout", "fall, fell"],
        ["kousat", "bite, bit"],
        ["ztratit", "lose, lost"],
        ["cítit", "feel, felt"],
        ["vzít", "take, took"],
        ["dostat", "get, got"],
        ["jít", "go, went"],
        ["mít", "have, had"],
        ["zranit", "hurt, hurt"],
        ["moci", "can, could"],
        ["číst", "read, read"],
        ["říci", "say, said"],
        ["přijít", "come, came"],
        ["spát", "sleep, slept"],
        ["psát", "write, wrote"],
        ["jíst", "eat, ate"],
        ["koupit", "buy, bought"],
        ["vidět", "see, saw"],
        ["řídit", "drive, drove"],
        ["plavat", "swim, swam"]
      ],
      "visible": true
    },
    {
      "code": "404",
      "title": "Angličtina 4 · Unit 3 + 4",
      "words": [
        ["byt", "apartment"],
        ["daleko", "far"],
        ["doufat", "hope"],
        ["nemocný", "ill"],
        ["volný", "off"],
        ["zábavný park", "theme park"],
        ["svatba", "wedding"],
        ["naštvaný", "angry"],
        ["myčka aut", "car wash"],
        ["vyzvednout (si)", "collect"],
        ["užívat si", "enjoy"],
        ["popadnout", "grab"],
        ["přistát", "land"],
        ["všimnout si", "notice"],
        ["zabalit", "pack"],
        ["zvednout, vzít", "pick up"],
        ["kapsa", "pocket"],
        ["křičet", "shout"],
        ["někdo jiný", "someone else"],
        ["cestovat", "travel"],
        ["vybalit", "unpack"],
        ["letiště", "airport"],
        ["kemp, tábořiště", "campsite"],
        ["štítek, visačka", "label"],
        ["zavazadlo", "luggage"],
        ["cestující", "passenger"],
        ["cestovní pas", "passport"],
        ["batoh", "rucksack"],
        ["ranvej", "runway"],
        ["kufr", "suitcase"],
        ["stan", "tent"],
        ["vozík", "trolley"]
      ],
      "visible": true
    },
    {
      "code": "403",
      "title": "Angličtina 4 · Animals",
      "words": [
        ["savci", "mammals"],
        ["obojživelníci", "amphibious"],
        ["ryby", "fish"],
        ["ptáci", "birds"],
        ["hmyzáci", "insects"],
        ["plazi", "reptiles"],
        ["křídlo", "wing"],
        ["pírka", "feathers"],
        ["zobák", "beak"],
        ["rohy", "horns"],
        ["kožich, kožešina", "fur"],
        ["ocas", "tail"],
        ["chobot", "trunk"],
        ["drápy", "claws"],
        ["šupiny", "scales"],
        ["žábry", "gills"],
        ["chlupy", "hairs"],
        ["kopyta", "hooves"],
        ["čenich", "snout"],
        ["hříbě", "foal"],
        ["štěně", "puppy"],
        ["tele", "calf"],
        ["kotě", "kitten"],
        ["kachňátko", "duckling"],
        ["prasátko", "piglet"],
        ["jehně", "lamb"],
        ["kůzle", "kid"]
      ],
      "visible": true
    },
    {
      "code": "402",
      "title": "Angličtina 4 · Unit 1",
      "words": [
        ["sfouknout", "blow out"],
        ["bowlingová dráha", "bowling alley"],
        ["svíčka", "candle"],
        ["slavit", "celebrate"],
        ["blízký k", "close to"],
        ["rozhodnout (se)", "decide"],
        ["slyšet", "hear"],
        ["důležitý", "important"],
        ["za ... dní", "in ... days'time"],
        ["seznam", "list"],
        ["přát si", "make a wish"],
        ["svátek", "name day"],
        ["ne moc", "not much"],
        ["problém", "problem"],
        ["dárek", "present"],
        ["někdo", "someone"],
        ["někde", "somewhere"],
        ["vzít", "take"],
        ["Vánoce", "Christmas"],
        ["Velikonoce", "Easter"],
        ["Nový rok", "New Year"]
      ],
      "visible": true
    },
    {
      "code": "401",
      "title": "Angličtina 4 · household jobs",
      "words": [
        ["naplnit myčku", "load the dishwasher"],
        ["vyvenčit psa", "take the dog for a walk"],
        ["uklidit si pokoj", "tidy your room"],
        ["vysát", "vacuum the floor"],
        ["vyhodit odpadky", "take out the recycling"],
        ["prostřít na stůl", "set the table"],
        ["ustlat si postel", "make the bed"],
        ["nakupovat", "do the shopping"],
        ["nakrmit kočku", "feed the cat"],
        ["uvařit večeři", "cook the dinner"]
      ],
      "visible": true
    },
    {
      "code": "306",
      "title": "Angličtina 3 · lekce 5B",
      "words": [
        ["koupelna", "bathroom"],
        ["sklep", "cellar"],
        ["jídelna", "dining room"],
        ["dole (v přízemí)", "downstairs"],
        ["garáž", "garage"],
        ["zahrada", "garden"],
        ["předsíň", "hall"],
        ["schody", "stairs"],
        ["záchod", "toilet"],
        ["nahoře (v patře)", "upstairs"],
        ["křeslo", "armchair"],
        ["vana", "bath"],
        ["vařič", "cooker"],
        ["skříňka", "cupboard"],
        ["záclona, závěs", "curtain"],
        ["lednička", "fridge"],
        ["světlo, lampa", "light"],
        ["dřez", "sink"],
        ["pohovka, gauč", "sofa"],
        ["umyvadlo", "washbasin"]
      ],
      "visible": true
    },
    {
      "code": "305",
      "title": "Angličtina 3 · lekce 5A",
      "words": [
        ["noční stolek", "bedside table"],
        ["polička na knihy", "bookshelf"],
        ["koberec", "carpet"],
        ["komoda", "chest of drawers"],
        ["kopačky", "football boots"],
        ["lampička", "lamp"],
        ["ztrcadlo", "mirror"],
        ["poloha, umístění", "position"],
        ["auto na dálkové ovládání", "remote-controlled car"],
        ["robot", "robot"],
        ["kobereček, předložka", "rug"],
        ["vidět", "see"],
        ["stěna, zeď", "wall"],
        ["šatní skříň", "wardrobe"]
      ],
      "visible": true
    },
    {
      "code": "304",
      "title": "Angličtina 3 · lekce 4",
      "words": [
        ["činnost", "activity"],
        ["hodiny", "clock"],
        ["koncert", "concert"],
        ["taneční, tanec", "dance"],
        ["zkouška", "exam"],
        ["hra", "game"],
        ["hokej", "hockey"],
        ["zápas, utkání", "match"],
        ["hodin (je X hodin)", "o'clock"],
        ["párty, večírek", "party"],
        ["piano, klavír", "piano"],
        ["tenis", "tennis"],
        ["volejbal", "volleyball"],
        ["Kolik je hodin?", "What's the time?"],
        ["po (časově)", "after"],
        ["dorazit do školy", "arrive at school"],
        ["o víkendu", "at the weekend"],
        ["před (časově)", "before"],
        ["snídaně", "breakfast"],
        ["vyčistit si zuby", "brush your teeth"],
        ["autobus", "bus"],
        ["kabát", "coat"],
        ["večeře", "dinner"]
      ],
      "visible": true
    },
    {
      "code": "303",
      "title": "Angličtina 3 · lekce 3",
      "words": [
        ["odpoledne", "afternoon"],
        ["shromáždění", "assembly"],
        ["přestávka", "break"],
        ["porovnat", "compare"],
        ["každý", "each"],
        ["dobrý v/na", "good at"],
        ["bezvadný", "great"],
        ["minulý, poslední", "last"],
        ["vyučovací hodina", "lesson"],
        ["příští, další", "next"],
        ["registrace", "registration"],
        ["předmět školní", "subject"],
        ["pololetí", "term"],
        ["rozvrh hodin", "timetable"],
        ["uniforma", "uniform"],
        ["nosit na sobě, oblékat", "wear"],
        ["rok", "year"],
        ["umění a design", "Art and Design"],
        ["biologie", "Biology"],
        ["chemie", "Chemistry"],
        ["občanská výchova", "Citizenship"],
        ["design a technologie, pracovní vyučování", "Design and Technology"],
        ["angličtina", "English"],
        ["francouzština", "French"],
        ["dějepis", "History"],
        ["informatika", "ICT (Information and Communication Technology)"],
        ["hudební výchova", "Music"],
        ["tělesná výchova", "PE (Physical Education)"],
        ["fyzika", "Physics"],
        ["náboženská výchova", "RE (Religious Education)"],
        ["věda", "Science"]
      ],
      "visible": true
    },
    {
      "code": "302",
      "title": "Angličtina 3 · lekce 2C",
      "words": [
        ["spolužák", "classmate"],
        ["promiňte", "excuse me"],
        ["přátelský", "friendly"],
        ["soused/ka", "neighbour"],
        ["silnice", "road"],
        ["zpěvák", "singer"],
        ["doma", "at home"],
        ["v obchodě, na nákupech", "at the shops"],
        ["volající", "caller"],
        ["píseň", "song"],
        ["dnes", "today"],
        ["týden", "week"],
        ["Kdy má narozeniny?", "When is his birthday?"]
      ],
      "visible": true
    },
    {
      "code": "301",
      "title": "Angličtina 3 · lekce 1",
      "words": [
        ["nashle, ahoj", "bye"],
        ["dobré odpoledne", "good afternoon"],
        ["na shledanou", "goodbye"],
        ["dobrý večer", "good evening"],
        ["dobré ráno", "good morning"],
        ["dobrou noc", "good night"],
        ["nazdar (vítání, loučení)", "hello"],
        ["ahoj (kamarádsky)", "hi"],
        ["jak se máš", "how are you"],
        ["naviděnou", "see yout"],
        ["buď opatrný", "be careful"],
        ["přijít", "come"],
        ["zdvojený, dvě", "double"],
        ["telefonní číslo", "phone number"],
        ["hrát (si)", "play"],
        ["jaké je tvoje telefonní číslo", "what's your phone number"],
        ["abeceda", "alphabet"],
        ["jak se píšeš", "how do you spell"],
        ["písmeno", "letter"],
        ["tam je", "there is"],
        ["tam jsou", "there are"]
      ],
      "visible": true
    },
    {
      "code": "250",
      "title": "Angličtina 2 · lekce 8",
      "words": [
        ["duben", "April"],
        ["srpen", "August"],
        ["podzim", "autumn"],
        ["vysoké boty", "boots"],
        ["mít hodně práce", "busy"],
        ["zataženo", "cloudy"],
        ["kabát", "coat"],
        ["prosinec", "December"],
        ["únor", "February"],
        ["povodeň", "flood"],
        ["mlhavo", "foggy"],
        ["horko", "hot"],
        ["leden", "January"],
        ["červenec", "July"],
        ["svetřík", "jumper"],
        ["červen", "June"],
        ["(u)dělat", "make"],
        ["březen", "March"],
        ["květen", "May"],
        ["listopad", "November"],
        ["říjen", "October"],
        ["venku", "outside"],
        ["deštivo", "rainy"],
        ["roční období", "season"],
        ["září", "September"],
        ["bota", "shoe"],
        ["sukně", "skirt"],
        ["jako", "spring"],
        ["léto", "summer"],
        ["slunečno", "sunny"],
        ["teplota", "temperature"],
        ["dnes", "today"],
        ["teplý", "warm"],
        ["počasí", "weather"],
        ["mokrý", "wet"],
        ["větrno", "windy"],
        ["zima", "winter"]
      ],
      "visible": true
    },
    {
      "code": "240",
      "title": "Angličtina 2 · lekce 7",
      "words": [
        ["mechanik", "mechanic"],
        ["muž rozvážející mléko", "milkman"],
        ["učitel hudby", "music teacher"],
        ["zdravotní sestra", "nurse"],
        ["administrativní pracovník", "office worker"],
        ["listonoš", "postman"],
        ["uniforma", "uniform"],
        ["nosit (oblékat)", "wear"],
        ["pracovat", "work"],
        ["kosmonaut", "astronaut"],
        ["astronaut", "astronomer"],
        ["klaun", "clown"],
        ["uniknout", "escape"],
        ["požární auto - stříkačka", "fire engine"],
        ["hasič", "firefighter"],
        ["obléci si", "get dressed"],
        ["vstávat", "get up"],
        ["jít spát", "go to bed"],
        ["dát si sprchu", "have a shower"],
        ["nemocnice", "hospital"],
        ["hladový", "hungry"],
        ["zaměstnání", "job"],
        ["pomocná policistka - zastavuje provoz", "lollipop lady"]
      ],
      "visible": true
    },
    {
      "code": "230",
      "title": "Angličtina 2 · lekce 6",
      "words": [
        ["program o zvířatech", "animal programme"],
        ["kreslený film", "cartoon"],
        ["televizní kanál", "channel"],
        ["zábavný pořad", "comedy show"],
        ["pořad o vaření", "cookery show"],
        ["pátek", "Friday"],
        ["soutěžní pořad", "game show"],
        ["domácí úkol", "homework"],
        ["zmeškat", "miss"],
        ["pondělí", "Monday"],
        ["jezdit (na kole)", "ride"],
        ["sobota", "Saturday"],
        ["sportovní pořad", "sports programme"],
        ["neděle", "Sunday"],
        ["televize", "television"],
        ["čtvrtek", "Thursday"],
        ["úterý", "Tuesday"],
        ["dívat se", "watch"],
        ["dívat se na televizi", "watching TV"],
        ["středa", "Wednesday"]
      ],
      "visible": true
    },
    {
      "code": "220",
      "title": "Angličtina 2 · lekce 5",
      "words": [
        ["kolo", "bike"],
        ["loď", "boat"],
        ["autobus", "bus"],
        ["kostel", "church"],
        ["kino", "cinema"],
        ["přejít", "cross"],
        ["trajekt", "ferry"],
        ["hasičský vůz", "fire engine"],
        ["drak (papírový)", "kite"],
        ["jezero", "lake"],
        ["vlevo", "left"],
        ["knihovna", "library"],
        ["park", "park"],
        ["kolem", "past"],
        ["restaurace", "restaurant"],
        ["vpravo", "right"],
        ["škola", "school"],
        ["sportovní centrum", "sports centre"],
        ["nádraží", "station"],
        ["přímo přes", "straight across"],
        ["supermarket", "supermarket"],
        ["jízdenka", "ticket"],
        ["hračkářství", "toy shop"],
        ["zahni/zahněte doleva", "turn left"],
        ["dodávka", "van"]
      ],
      "visible": true
    },
    {
      "code": "210",
      "title": "Angličtina 2 · lekce 4",
      "words": [
        ["mezi, uprostřed", "between"],
        ["větší", "bigger"],
        ["parkoviště", "car park"],
        ["vynikající (chutné)", "delicious"],
        ["farma", "farm"],
        ["tlustší", "fatter"],
        ["koza", "goat"],
        ["hora", "mountain"],
        ["vedle", "next to"],
        ["stejný", "same"],
        ["kratší", "shorter"],
        ["pomalý", "slow"],
        ["menší", "smaller"],
        ["silný", "strong"],
        ["vyšší", "taller"],
        ["hubenější", "thinner"],
        ["záchody", "toilets"]
      ],
      "visible": true
    },
    {
      "code": "203",
      "title": "Angličtina 2 · určování času EN → CZ",
      "words": [
        ["quarter to one", "12:45"],
        ["twenty past eleven", "11:20"],
        ["eleven o'clock", "11:00"],
        ["half past eight", "8:30"],
        ["twenty past eight", "8:20"],
        ["quarter past six", "6:15"],
        ["twenty-five to four", "3:35"],
        ["quarter to two", "1:45"],
        ["twenty-five past one", "1:25"],
        ["half past ten", "10:30"]
      ],
      "visible": true
    },
    {
      "code": "204",
      "title": "Angličtina 2 · určování času CZ → EN",
      "words": [
        ["10:05 (bez minutes)", "five past ten"],
        ["3:57 (s minutes)", "three minutes to four"],
        ["4:13 (s minutes)", "thirteen minutes past four"],
        ["7:16 (s minutes)", "sixteen minutes past seven"],
        ["2:04 (s minutes)", "four minutes past two"],
        ["3:40 (bez minutes)", "twenty to four"],
        ["12:38 (s minutes)", "twenty-two minutes to one"],
        ["9:10 (bez minutes)", "ten past nine"],
        ["9:28 (s minutes)", "twenty-eight minutes past nine"],
        ["8:45", "quarter to nine"],
        ["3:00", "three o'clock"]
      ],
      "visible": true
    },
    {
      "code": "205",
      "title": "Angličtina 2 · lekce 3",
      "words": [
        ["banán", "banana"],
        ["chleba", "bread"],
        ["snídaně", "breakfast"],
        ["cereálie", "cereal"],
        ["sýr", "cheese"],
        ["brambůrky", "crisps"],
        ["večeře", "dinner"],
        ["vajíčka", "eggs"],
        ["hroznové víno", "grapes"],
        ["oběd", "lunch"],
        ["slanina", "bacon"],
        ["fazole", "beans"],
        ["máslo", "butter"],
        ["káva", "coffee"],
        ["okurek", "cucumber"],
        ["džem", "jam"],
        ["citronáda", "lemonade"],
        ["hlávkový salát", "lettuce"],
        ["jídlo", "meal"],
        ["houby", "mushrooms"],
        ["cibule", "onion"],
        ["rýže", "rice"],
        ["salát", "salad"],
        ["sendvič", "sandwich"],
        ["párek", "sausage"],
        ["polévka", "soup"],
        ["jahoda", "strawberry"],
        ["čaj", "tea"],
        ["toast", "toast"],
        ["rajčata", "tomatoes"],
        ["tuňák", "tuna"],
        ["zelenina", "vegetable"],
        ["jogurt", "yoghurt"],
        ["vynikající (chutné)", "delicious"]
      ],
      "visible": true
    },
    {
      "code": "202",
      "title": "Angličtina 2 · lekce 2",
      "words": [
        ["oslava výročí", "anniversary"],
        ["dárek", "present"],
        ["náhrdelník", "necklace"],
        ["kravata", "tie"],
        ["babička", "grandma"],
        ["dědeček", "grandpa"],
        ["bratr", "brother"],
        ["sestra", "sister"],
        ["teta", "aunt"],
        ["bratranec, sestřenice", "cousin"],
        ["obrovský", "giant"],
        ["příbuzní", "relatives"],
        ["dvojčata", "twins"],
        ["strýc", "uncle"],
        ["rodina", "family"],
        ["rodiče", "parents"]
      ],
      "visible": true
    },
    {
      "code": "201",
      "title": "Angličtina 2 · lekce 1",
      "words": [
        ["byt", "flat"],
        ["stopy (otisky nohou)", "footprints"],
        ["garáž", "garage"],
        ["vědět, znát", "know"],
        ["štěnátka", "puppies"],
        ["hláskovat", "spell"],
        ["ulice", "street"]
      ],
      "visible": true
    },
    {
      "code": "107",
      "title": "Angličtina 1 · lekce 7",
      "words": [
        ["nejlepší", "best"],
        ["blonďatý", "blond"],
        ["chlapec", "boy"],
        ["autobusová zastávka", "bus stop"],
        ["kavárna", "café"],
        ["dcera", "daughter"],
        ["tlustý", "fat"],
        ["děvče", "girl"],
        ["brýle", "glasses"],
        ["dlouhý", "long"],
        ["muž", "man"],
        ["muzeum", "museum"],
        ["starý", "old"],
        ["vysoký", "tall"],
        ["hubený", "thin"],
        ["žena", "woman"],
        ["mladý", "young"],
        ["nejlepší blonďatý chlapec", "best blond boy"]
      ],
      "visible": true
    },
    {
      "code": "106",
      "title": "Angličtina 1 · lekce 6",
      "words": [
        ["koupelna", "bathroom"],
        ["ložnice", "bedroom"],
        ["obývací pokoj (zde se žije)", "living room"],
        ["obývací pokoj (zde se sedí)", "siting room"],
        ["kuchyně", "kitchen"],
        ["peří", "feathers"],
        ["v", "in"],
        ["na", "on"],
        ["pod", "under"],
        ["postel", "bed"],
        ["knihovna", "bookcase"],
        ["postele (nad sebou)", "bunk bed"],
        ["židle", "chair"],
        ["skříňka", "cupboard"],
        ["krb", "fireplace"],
        ["kobereček", "rug"],
        ["gauč", "sofa"],
        ["stůl", "table"],
        ["krabice na hračky", "toy box"]
      ],
      "visible": true
    },
    {
      "code": "105",
      "title": "Angličtina 1 · lekce 5",
      "words": [
        ["míč", "ball"],
        ["velký", "big"],
        ["kolo", "bike"],
        ["fotbal", "football"],
        ["papírový drak", "kite"],
        ["poslouchat", "listen"],
        ["podívat se", "look"],
        ["letadlo", "plane"],
        ["hrát si", "play"],
        ["závodní auto", "racing car"],
        ["skateboard", "skateboard"],
        ["malý", "small"]
      ],
      "visible": true
    },
    {
      "code": "104",
      "title": "Angličtina 1 · lekce 4",
      "words": [
        ["banán", "banana"],
        ["dortík", "cake"],
        ["hruška", "pear"],
        ["jablko", "apple"],
        ["pomeranč", "orange"],
        ["zmrzlina", "ice cream"],
        ["sušenky", "biscuits"],
        ["snídaně", "breakfast"],
        ["čokoláda", "chocolate"],
        ["citron", "lemon"],
        ["oběd", "lunch"],
        ["mléko", "milk"],
        ["houby", "mushrooms"],
        ["olivy", "olives"],
        ["těstoviny", "pasta"],
        ["paprika", "peppers"],
        ["piza", "pizza"],
        ["svačina", "snack"],
        ["sladkosti", "sweets"],
        ["čaj", "tea"],
        ["sendvič", "sandwich"],
        ["sýr", "cheese"]
      ],
      "visible": true
    },
    {
      "code": "N3",
      "title": "Angličtina 1 · číslovky 21 až 100",
      "words": [
        ["Číslo 21", "twenty-one"],
        ["Číslo 22", "twenty-two"],
        ["Číslo 23", "twenty-three"],
        ["Číslo 28", "twenty-eight"],
        ["Číslo 30", "thirty"],
        ["Číslo 33", "thirty-three"],
        ["Číslo 35", "thirty-five"],
        ["Číslo 40", "forty"],
        ["Číslo 42", "forty-two"],
        ["Číslo 43", "forty-three"],
        ["Číslo 52", "fifty-two"],
        ["Číslo 55", "fifty-five"],
        ["Číslo 57", "fifty-seven"],
        ["Číslo 58", "fifty-eight"],
        ["Číslo 59", "fifty-nine"],
        ["Číslo 60", "sixty"],
        ["Číslo 63", "sixty-three"],
        ["Číslo 67", "sixty-seven"],
        ["Číslo 68", "sixty-eight"],
        ["Číslo 71", "seventy-one"],
        ["Číslo 72", "seventy-two"],
        ["Číslo 74", "seventy-four"],
        ["Číslo 75", "seventy-five"],
        ["Číslo 79", "seventy-nine"],
        ["Číslo 82", "eighty-two"],
        ["Číslo 83", "eighty-three"],
        ["Číslo 84", "eighty-four"],
        ["Číslo 92", "ninety-two"],
        ["Číslo 94", "ninety-four"],
        ["Číslo 96", "ninety-six"],
        ["Číslo 100", "one hundred"]
      ],
      "visible": true
    },
    {
      "code": "N2",
      "title": "Angličtina 1 · číslovky 10 až 20",
      "words": [
        ["Číslo 10", "ten"],
        ["Číslo 11", "eleven"],
        ["Číslo 12", "twelve"],
        ["Číslo 13", "thirteen"],
        ["Číslo 14", "fourteen"],
        ["Číslo 15", "fifteen"],
        ["Číslo 16", "sixteen"],
        ["Číslo 17", "seventeen"],
        ["Číslo 18", "eighteen"],
        ["Číslo 19", "nineteen"],
        ["Číslo 20", "twenty"]
      ],
      "visible": true
    },
    {
      "code": "N1",
      "title": "Angličtina 1 · číslovky 0 až 9",
      "words": [
        ["Číslo 0", "zero"],
        ["Číslo 1", "one"],
        ["Číslo 2", "two"],
        ["Číslo 3", "three"],
        ["Číslo 4", "four"],
        ["Číslo 5", "five"],
        ["Číslo 6", "six"],
        ["Číslo 7", "seven"],
        ["Číslo 8", "eight"],
        ["Číslo 9", "nine"]
      ],
      "visible": true
    },
    {
      "code": "C1",
      "title": "Čeština · vyjmenovaná slova po M",
      "words": [
        ["my", "my"],
        ["mýt", "mýt"],
        ["myslet", "myslet"],
        ["mýlit se", "mýlit se"],
        ["hmyz", "hmyz"],
        ["myš", "myš"],
        ["hlemýžď", "hlemýžď"],
        ["mýtit", "mýtit"],
        ["zamykat", "zamykat"],
        ["smýkat", "smýkat"],
        ["dmýchat", "dmýchat"],
        ["chmýří", "chmýří"],
        ["nachomýtnout se", "nachomýtnout se"],
        ["litomyšl", "litomyšl"]
      ],
      "visible": true
    },
    {
      "code": "C2",
      "title": "Čeština · ě / je",
      "words": [
        ["napsaný příb_h", "ě"],
        ["průb_h vyšetřování", "ě"],
        ["ob_vit viníky", "je"],
        ["ztráta v_domí", "ě"],
        ["ob_mný balík", "je"],
        ["v_rný pes", "ě"],
        ["v_zd do dvora", "je"],
        ["odpov_dný člověk", "ě"],
        ["ob_vení Ameriky", "je"],
        ["zrakový v_m", "je"],
        ["výb_h dobytka", "ě"],
        ["maminčino ob_tí", "je"],
        ["kv_ty bylinek", "ě"],
        ["b_žet po pěšině", "ě"],
        ["osv_žující nápoj", "ě"],
        ["v_řit v Boha", "ě"],
        ["ob_m tělesa", "je"],
        ["úsp_šný běžec", "ě"],
        ["ob_dnat časopis", "je"],
        ["přispět k ob_vu", "je"],
        ["Věra a B_tka", "ě"],
        ["Kv_ta", "ě"],
        ["zákaz v_zdu", "je"],
        ["vrať se zp_t", "ě"],
        ["správná odpov_ď", "ě"],
        ["vysoké nap_tí", "ě"],
        ["sb_r papíru", "ě"],
        ["na hlav_", "ě"],
        ["v_žní hodiny", "ě"],
        ["pes zav_třil zloděje", "ě"],
        ["ob_dnávka zboží", "je"],
        ["pouštět v_nečky", "ě"],
        ["krůp_je rosy", "ě"],
        ["divoká zv_ř", "ě"],
        ["poup_ růže", "ě"],
        ["v_rný přítel", "ě"],
        ["záv_je sněhu", "ě"],
        ["vlčí doup_", "ě"]
      ],
      "visible": true
    }
  ]
};
